{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "manticore.fullname" . }}
  labels:
    app: {{ template "manticore.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "manticore.name" . }}
    release: {{ .Release.Name }}
  ports:
{{- range $port := .Values.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.port }}
    protocol: {{ $port.protocol }}
    targetPort: {{ $port.targetPort }}
{{- end }}     
{{- end }}
